Fix pep8 Zuul failure
A new version of flake8 (6.0.0) was released Nov 23, 2022
It is leading to an argparse error
  ValueError: 'string' is not callable

The fix is to use 'hacking' which is an openstack module
that pulls in the appropriate version of flake8.

Closes-Bug: #1997971
Signed-off-by: Al Bailey <al.bailey@windriver.com>
Change-Id: Icaa5cd1cb7c362bd8caf666d82d7d7f655523fb0